---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "6.7"}

run:
  path: ci/tasks/build-js.sh
  dir: app-master

inputs:
  - name: app-master

outputs:
  - name: built-project-js
